name: Tests & Checks

on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "**/*.md"
  push:
    branches:
      - master
      - main
    paths-ignore:
      - ".github/**"
      - "**/*.md"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write

jobs:

  checks:

    name: Checks
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        toolchain:
          - stable

    env:
      RUST_BACKTRACE: full

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          submodules: recursive
          show-progress: false

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
          cache-key-job: true

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

      - name: Check check
        run: cargo check --workspace --all-features

      - name: Check clippy
        run: cargo clippy --workspace --all-features

      - name: Check build
        run: cargo build --all-features --verbose

      - name: Check build (i686-pc-windows-msvc)
        if: runner.os == 'Windows'
        run: |
          rustup target add i686-pc-windows-msvc
          cargo build --target i686-pc-windows-msvc --all-features --verbose

  formatting:

    name: Formatting
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          submodules: recursive
          show-progress: false

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          cache-key-job: true

      - name: Check formatting
        run: cargo fmt --all -- --check
